CI: azure
c_compiler: gcc
c_compiler_version: '9'
cdt_name: cos6
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-comp7
extend_keys:
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
ncurses: '6.2'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  ncurses:
    max_pin: x.x
  readline:
    max_pin: x
  zlib:
    max_pin: x.x
python: '3.8'
r_base: '3.5'
readline: '8'
target_platform: linux-64
zip_keys:
- - cdt_name
  - docker_image
zlib: '1.2'
