# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Oct 27 10:33:55 2021
# ------------------------------------------------

package:
  name: tqdm
  version: 4.62.3
source:
  sha256: d359de7217506c9851b7869f3708d8ee53ed70a1b8edbba4dbcb47442592920d
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.62.3.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  noarch: python
  number: '1'
  script: /tmp/build/80754af9/tqdm_1635330843403/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.9.30 h06a4308_1
    - certifi 2021.10.8 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py39h06a4308_0
    - setuptools-scm 6.0.1 pyhd3eb1b0_1
    - setuptools_scm 6.0.1 hd3eb1b0_1
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=2.7
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
    - python <3.10
  source_files:
    - pyproject.toml
    - setup.cfg
    - tests
about:
  dev_url: https://github.com/tqdm/tqdm
  doc_source_url: https://github.com/tqdm/tqdm/blob/master/README.rst
  doc_url: https://github.com/tqdm/tqdm#tqdm
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
