# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/requests-2.26.0-on-linux_64, last modified Thu Aug 26 18:36:37 2021
# ------------------------------------------------

package:
  name: requests
  version: 2.26.0
source:
  sha256: b8aa58f8cf793ffd8782d3d8cb19e66ef36f7aba4353eec859e74678b01b07a7
  url: https://pypi.io/packages/source/r/requests/requests-2.26.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/requests_1629994808627/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.7.5 h06a4308_1
    - certifi 2021.5.30 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.2.4 py37h06a4308_0
    - python 3.9.6 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.37.0 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - certifi >=2017.4.17
    - charset-normalizer >=2.0.0,<2.1.0
    - idna >=2.5,<4
    - python >=3.6
    - urllib3 >=1.21.1,<1.27
test:
  commands:
    - pip check
  imports:
    - requests
  requires:
    - pip
about:
  description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

    consumption.

    '
  dev_url: https://github.com/psf/requests
  doc_url: http://docs.python-requests.org/
  home: http://python-requests.org
  license: Apache-2.0
  license_file: LICENSE
  summary: "Requests is an elegant and simple HTTP library for Python, built with\
    \ \u2665."
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - sigmavirus24
