# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Oct 27 11:11:32 2021
# ------------------------------------------------

package:
  name: pyopenssl
  version: 21.0.0
source:
  sha256: 5e2d8c5e46d0d865ae933bef5230090bdaf5506281e9eec60fa250ee80600cb3
  url: https://pypi.io/packages/source/p/pyOpenSSL/pyOpenSSL-21.0.0.tar.gz
build:
  noarch: python
  number: '1'
  script: /tmp/build/80754af9/pyopenssl_1635333100036/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vvv
  string: pyhd3eb1b0_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.9.30 h06a4308_1
    - certifi 2021.10.8 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - cryptography >=3.3
    - python
    - six >=1.5.2
test:
  commands:
    - pip check
  imports:
    - OpenSSL
    - OpenSSL.SSL
    - OpenSSL.crypto
    - OpenSSL.rand
  requires:
    - pip
    - python <3.10
about:
  description: 'pyOpenSSL is a high-level wrapper around a subset of the OpenSSL library.

    It includes:

    -SSL.Connection objects, wrapping the methods of Python''s portable sockets

    -Callbacks written in Python

    -Extensive error-handling mechanism, mirroring OpenSSL''s error codes

    and much more.

    '
  dev_url: https://github.com/pyca/pyopenssl
  doc_source_url: https://github.com/pyca/pyopenssl/blob/master/doc/index.rst
  doc_url: https://pyopenssl.readthedocs.org/en/stable/
  home: https://github.com/pyca/pyopenssl
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper module around the OpenSSL library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - mingwandroid
    - nehaljwani
