# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libblas
  version: 3.9.0
source:
  patches:
    - patches/0001-Test-BLAS-and-LAPACKE-in-addition-to-LAPACK.patch
  sha256: 106087f1bb5f46afdfba7f569d0cbe23dacb9a07cd24733765a0e89dbe1ad573
  url: https://github.com/Reference-LAPACK/lapack/archive/v3.9.0.tar.gz
build:
  number: 12
  run_exports:
    - libblas >=3.9.0,<4.0a0
  string: 12_linux64_openblas
  track_features: null
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgfortran-ng 11.2.0 h69a702a_11
    - libgfortran5 11.2.0 h5c6108e_11
    - libgomp 11.2.0 h1d223b6_11
    - libopenblas 0.3.18 pthreads_h8fe5266_0
  run:
    - libopenblas >=0.3.18,<0.3.19.0a0
    - libopenblas >=0.3.18,<1.0a0
  run_constrained:
    - blas * openblas
    - libcblas 3.9.0 12_linux64_openblas
    - liblapack 3.9.0 12_linux64_openblas
    - liblapacke 3.9.0 12_linux64_openblas
test:
  commands:
    - test -f $PREFIX/lib/libblas.so.3
about:
  home: https://github.com/conda-forge/blas-feedstock
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  summary: Metapackage to select the BLAS variant. Use conda's pinning mechanism in
    your environment to control which variant you want.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - h-vetinari
    - isuruf
    - jakirkham
    - ocefpaf
    - pelson
