# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Sep 23 07:29:57 2021
# ------------------------------------------------

package:
  name: python
  version: 3.6.13
source:
  - patches:
      - 0002-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
      - 0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - 0004-Win32-distutils-Also-look-for-executable.bat.patch
      - 0005-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch
      - 0006-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - 0007-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - 0008-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - 0009-Support-cross-compiling-byte-code.patch
      - 0010-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - 0011-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - 0012-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - 0013-Win32-Do-not-download-externals.patch
      - 0014-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - 0015-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - 0016-Disable-new-dtags-in-unixccompiler.py.patch
      - 0017-Fix-cross-compilation-on-Debian-based-distros.patch
      - 0020-Use-ranlib-from-env-if-env-variable-is-set.patch
    sha256: a47a43a53abb42286a2c11965343ff56711b9e64e8d11bf2c6701a4fb8ce1a0f
    url: https://www.python.org/ftp/python/3.6.13/Python-3.6.13.tar.xz
build:
  ignore_run_exports:
    - bzip2
  no_link:
    - bin/python3.6
  number: '2'
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.6.* *_cp36m
  string: hb7a2778_2_cpython
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_1
    - gcc_impl_linux-64 9.4.0 h03d3576_8
    - gcc_linux-64 9.4.0 h391b98a_1
    - gxx_impl_linux-64 9.4.0 h03d3576_8
    - gxx_linux-64 9.4.0 h0316aca_1
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.4.0 hd854feb_8
    - libgcc-ng 11.2.0 h1d223b6_8
    - libgomp 11.2.0 h1d223b6_8
    - libsanitizer 9.4.0 h79bfe98_8
    - libstdcxx-devel_linux-64 9.4.0 hd854feb_8
    - libstdcxx-ng 11.2.0 he4da1e4_8
    - libx11-common-cos6-x86_64 1.6.4 h9b0a68f_1105
    - libx11-cos6-x86_64 1.6.4 h9b0a68f_1105
    - libx11-devel-cos6-x86_64 1.6.4 h9b0a68f_1105
    - make 4.3 hd18ef5c_1
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_14
    - xorg-x11-proto-devel-cos6-x86_64 7.7 h9b0a68f_1105
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.5.30 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h9c3ff4c_3
    - libgcc-ng 11.2.0 h1d223b6_8
    - libgomp 11.2.0 h1d223b6_8
    - libstdcxx-ng 11.2.0 he4da1e4_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1l h7f98852_0
    - readline 8.1 h46c0cb4_0
    - sqlite 3.36.0 h9cd32fc_1
    - tk 8.6.11 h27826a3_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - ld_impl_linux-64 >=2.34
    - libffi >=3.4.2,<3.5.0a0
    - libgcc-ng >=9.4.0
    - libstdcxx-ng >=9.4.0
    - ncurses >=6.2,<6.3.0a0
    - ncurses >=6.2,<6.3.0a0
    - openssl >=1.1.1l,<1.1.2a
    - readline >=8.1,<9.0a0
    - sqlite >=3.36.0,<4.0a0
    - tk >=8.6.11,<8.7.0a0
    - xz >=5.2.5,<5.3.0a0
    - zlib >=1.2.11,<1.3.0a0
  run_constrained:
    - python_abi 3.6.* *_cp36m
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_linux_gnu python
      -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - python -c "import sys; files = [f for f in sys.argv[2:] if ' -partition=none'
      in open(f, 'r').read()]; assert len(files) == 0, files" ${PREFIX}/lib/*/*.py
    - test -f ${PREFIX}/lib/libpython3.6m.so
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: http://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
